# Generated by Django 6.0.1 on 2026-02-03 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('deacons', models.ManyToManyField(blank=True, related_name='district_deacons', to=settings.AUTH_USER_MODEL)),
                ('elder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elder_district', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_secretary', to=settings.AUTH_USER_MODEL)),
                ('treasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_treasurer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
