# Generated by Django 6.0.1 on 2026-02-03 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('patron', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patron_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary', 'Secretary'), ('Vice Secretary', 'Vice Secretary'), ('Treasurer', 'Treasurer'), ('Vice Treasurer', 'Vice Treasurer')], max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'role')},
            },
        ),
    ]
