/**
 * Mock Data Service for Covenant Cloud Church Management System
 * This provides realistic sample data for all modules
 */

// ─── MEMBERS ────────────────────────────────────────────────────────────────
export const mockMembers = [
  {
    id: 1,
    name: "Rev. James Mwangi",
    email: "james.mwangi@church.org",
    phone: "+254 712 345 678",
    role: "pastor",
    status: "active",
    joinDate: "2015-03-12",
    address: "123 Church Rd, Nairobi",
    gender: "Male",
    dob: "1975-06-20",
    baptized: true,
    group: "Main Congregation",
  },
  {
    id: 2,
    name: "Elder Samuel Kariuki",
    email: "samuel.kariuki@church.org",
    phone: "+254 723 456 789",
    role: "elder",
    status: "active",
    joinDate: "2016-07-08",
    address: "45 Faith Ave, Nairobi",
    gender: "Male",
    dob: "1968-11-15",
    baptized: true,
    group: "Men's Fellowship",
  },
  {
    id: 3,
    name: "Mrs. Grace Wanjiku",
    email: "grace.wanjiku@church.org",
    phone: "+254 734 567 890",
    role: "treasurer",
    status: "active",
    joinDate: "2017-01-22",
    address: "78 Hope St, Nairobi",
    gender: "Female",
    dob: "1980-04-30",
    baptized: true,
    group: "Women's Guild",
  },
  {
    id: 4,
    name: "Mr. Peter Ochieng",
    email: "peter.ochieng@church.org",
    phone: "+254 745 678 901",
    role: "registrar",
    status: "active",
    joinDate: "2018-05-14",
    address: "12 Grace Blvd, Nairobi",
    gender: "Male",
    dob: "1985-09-10",
    baptized: true,
    group: "Main Congregation",
  },
  {
    id: 5,
    name: "Ms. Faith Akinyi",
    email: "faith.akinyi@church.org",
    phone: "+254 756 789 012",
    role: "deputy_registrar",
    status: "active",
    joinDate: "2019-09-03",
    address: "56 Blessing Rd, Nairobi",
    gender: "Female",
    dob: "1990-02-14",
    baptized: true,
    group: "Youth Fellowship",
  },
  {
    id: 6,
    name: "Mr. David Kamau",
    email: "david.kamau@church.org",
    phone: "+254 767 890 123",
    role: "member",
    status: "active",
    joinDate: "2020-02-18",
    address: "89 Praise Lane, Nairobi",
    gender: "Male",
    dob: "1995-07-25",
    baptized: true,
    group: "Youth Fellowship",
  },
  {
    id: 7,
    name: "Mrs. Mary Njeri",
    email: "mary.njeri@church.org",
    phone: "+254 778 901 234",
    role: "member",
    status: "active",
    joinDate: "2020-06-30",
    address: "34 Worship Way, Nairobi",
    gender: "Female",
    dob: "1988-12-05",
    baptized: true,
    group: "Women's Guild",
  },
  {
    id: 8,
    name: "Mr. John Otieno",
    email: "john.otieno@church.org",
    phone: "+254 789 012 345",
    role: "member",
    status: "inactive",
    joinDate: "2021-03-15",
    address: "67 Mercy St, Nairobi",
    gender: "Male",
    dob: "1992-03-18",
    baptized: false,
    group: "Main Congregation",
  },
  {
    id: 9,
    name: "Ms. Ruth Wambui",
    email: "ruth.wambui@church.org",
    phone: "+254 790 123 456",
    role: "member",
    status: "active",
    joinDate: "2021-08-22",
    address: "23 Love Ave, Nairobi",
    gender: "Female",
    dob: "1997-08-22",
    baptized: true,
    group: "PCMF",
  },
  {
    id: 10,
    name: "Mr. Joseph Mutua",
    email: "joseph.mutua@church.org",
    phone: "+254 701 234 567",
    role: "member",
    status: "active",
    joinDate: "2022-01-10",
    address: "90 Peace Rd, Nairobi",
    gender: "Male",
    dob: "1993-05-11",
    baptized: true,
    group: "PCMF",
  },
  {
    id: 11,
    name: "Elder Thomas Njoroge",
    email: "thomas.njoroge@church.org",
    phone: "+254 712 345 679",
    role: "elder",
    status: "active",
    joinDate: "2014-11-05",
    address: "15 Covenant St, Nairobi",
    gender: "Male",
    dob: "1965-01-28",
    baptized: true,
    group: "Men's Fellowship",
  },
  {
    id: 12,
    name: "Mrs. Esther Wangari",
    email: "esther.wangari@church.org",
    phone: "+254 723 456 780",
    role: "member",
    status: "active",
    joinDate: "2022-05-20",
    address: "48 Salvation Blvd, Nairobi",
    gender: "Female",
    dob: "1986-10-17",
    baptized: true,
    group: "Women's Guild",
  },
];

// ─── DONATIONS ───────────────────────────────────────────────────────────────
export const mockDonations = [
  {
    id: 1,
    donor: "John Otieno",
    amount: 5000,
    type: "Tithe",
    date: "2026-02-01",
    method: "M-Pesa",
    reference: "MP001234",
    status: "confirmed",
    notes: "",
  },
  {
    id: 2,
    donor: "Mary Njeri",
    amount: 2000,
    type: "Offering",
    date: "2026-02-01",
    method: "Cash",
    reference: "CSH001",
    status: "confirmed",
    notes: "",
  },
  {
    id: 3,
    donor: "David Kamau",
    amount: 10000,
    type: "Special Offering",
    date: "2026-02-08",
    method: "Bank Transfer",
    reference: "BNK00456",
    status: "confirmed",
    notes: "Building Fund",
  },
  {
    id: 4,
    donor: "Ruth Wambui",
    amount: 1500,
    type: "Tithe",
    date: "2026-02-08",
    method: "M-Pesa",
    reference: "MP001235",
    status: "confirmed",
    notes: "",
  },
  {
    id: 5,
    donor: "Joseph Mutua",
    amount: 3000,
    type: "Offering",
    date: "2026-02-15",
    method: "Cash",
    reference: "CSH002",
    status: "confirmed",
    notes: "",
  },
  {
    id: 6,
    donor: "Esther Wangari",
    amount: 7500,
    type: "Tithe",
    date: "2026-02-15",
    method: "M-Pesa",
    reference: "MP001236",
    status: "pending",
    notes: "",
  },
  {
    id: 7,
    donor: "Peter Ochieng",
    amount: 20000,
    type: "Pledge",
    date: "2026-02-22",
    method: "Bank Transfer",
    reference: "BNK00457",
    status: "confirmed",
    notes: "Annual pledge",
  },
  {
    id: 8,
    donor: "Faith Akinyi",
    amount: 4000,
    type: "Tithe",
    date: "2026-02-22",
    method: "M-Pesa",
    reference: "MP001237",
    status: "confirmed",
    notes: "",
  },
  {
    id: 9,
    donor: "Anonymous",
    amount: 50000,
    type: "Special Offering",
    date: "2026-02-22",
    method: "Bank Transfer",
    reference: "BNK00458",
    status: "confirmed",
    notes: "Renovation Fund",
  },
  {
    id: 10,
    donor: "Samuel Kariuki",
    amount: 8000,
    type: "Tithe",
    date: "2026-02-27",
    method: "M-Pesa",
    reference: "MP001238",
    status: "pending",
    notes: "",
  },
];

// ─── EVENTS ──────────────────────────────────────────────────────────────────
export const mockEvents = [
  {
    id: 1,
    title: "Sunday Morning Service",
    date: "2026-03-01",
    time: "09:00 AM",
    location: "Main Sanctuary",
    type: "Worship",
    organizer: "Rev. James Mwangi",
    attendees: 250,
    status: "upcoming",
    description:
      "Weekly Sunday worship service with praise and worship, sermon, and Holy Communion.",
  },
  {
    id: 2,
    title: "Mid-Week Bible Study",
    date: "2026-03-04",
    time: "06:00 PM",
    location: "Fellowship Hall",
    type: "Bible Study",
    organizer: "Elder Samuel Kariuki",
    attendees: 80,
    status: "upcoming",
    description: "In-depth Bible study on the Book of Romans.",
  },
  {
    id: 3,
    title: "Youth Fellowship Meeting",
    date: "2026-03-07",
    time: "03:00 PM",
    location: "Youth Center",
    type: "Fellowship",
    organizer: "Ms. Faith Akinyi",
    attendees: 45,
    status: "upcoming",
    description: "Monthly youth fellowship with games, worship, and devotion.",
  },
  {
    id: 4,
    title: "Women's Guild Meeting",
    date: "2026-03-10",
    time: "10:00 AM",
    location: "Conference Room A",
    type: "Meeting",
    organizer: "Mrs. Grace Wanjiku",
    attendees: 35,
    status: "upcoming",
    description: "Monthly women's guild meeting and prayer session.",
  },
  {
    id: 5,
    title: "Easter Sunday Service",
    date: "2026-04-05",
    time: "07:00 AM",
    location: "Main Sanctuary",
    type: "Special Service",
    organizer: "Rev. James Mwangi",
    attendees: 500,
    status: "upcoming",
    description: "Easter sunrise service followed by breakfast fellowship.",
  },
  {
    id: 6,
    title: "Annual Church Fundraiser",
    date: "2026-04-18",
    time: "11:00 AM",
    location: "Church Grounds",
    type: "Fundraiser",
    organizer: "Mrs. Grace Wanjiku",
    attendees: 300,
    status: "upcoming",
    description: "Annual fundraiser for church building expansion project.",
  },
  {
    id: 7,
    title: "Sunday Morning Service",
    date: "2026-02-22",
    time: "09:00 AM",
    location: "Main Sanctuary",
    type: "Worship",
    organizer: "Rev. James Mwangi",
    attendees: 230,
    status: "completed",
    description: "Weekly Sunday worship service.",
  },
  {
    id: 8,
    title: "Choir Practice",
    date: "2026-02-25",
    time: "05:00 PM",
    location: "Music Room",
    type: "Practice",
    organizer: "Mr. David Kamau",
    attendees: 20,
    status: "completed",
    description: "Weekly choir rehearsal for Sunday service.",
  },
];

// ─── PRAYER REQUESTS ─────────────────────────────────────────────────────────
export const mockPrayerRequests = [
  {
    id: 1,
    requester: "Mary Njeri",
    request: "Please pray for my mother who is recovering from surgery.",
    category: "Health",
    date: "2026-02-25",
    status: "active",
    isAnonymous: false,
    prayedFor: 12,
  },
  {
    id: 2,
    requester: "Anonymous",
    request: "Pray for my family to find peace and reconciliation.",
    category: "Family",
    date: "2026-02-24",
    status: "active",
    isAnonymous: true,
    prayedFor: 8,
  },
  {
    id: 3,
    requester: "David Kamau",
    request: "Seeking God's guidance for a major career decision.",
    category: "Guidance",
    date: "2026-02-23",
    status: "active",
    isAnonymous: false,
    prayedFor: 15,
  },
  {
    id: 4,
    requester: "Ruth Wambui",
    request: "Pray for my studies and upcoming exams.",
    category: "Education",
    date: "2026-02-22",
    status: "active",
    isAnonymous: false,
    prayedFor: 20,
  },
  {
    id: 5,
    requester: "Joseph Mutua",
    request: "Pray for financial breakthrough and provision.",
    category: "Financial",
    date: "2026-02-20",
    status: "answered",
    isAnonymous: false,
    prayedFor: 25,
  },
  {
    id: 6,
    requester: "Anonymous",
    request: "Pray for healing from chronic illness.",
    category: "Health",
    date: "2026-02-18",
    status: "active",
    isAnonymous: true,
    prayedFor: 30,
  },
  {
    id: 7,
    requester: "Esther Wangari",
    request: "Pray for my marriage and family unity.",
    category: "Family",
    date: "2026-02-15",
    status: "answered",
    isAnonymous: false,
    prayedFor: 18,
  },
  {
    id: 8,
    requester: "Peter Ochieng",
    request: "Pray for the church leadership and vision.",
    category: "Church",
    date: "2026-02-10",
    status: "active",
    isAnonymous: false,
    prayedFor: 45,
  },
];

// ─── SERMONS ─────────────────────────────────────────────────────────────────
export const mockSermons = [
  {
    id: 1,
    title: "Walking in Faith",
    preacher: "Rev. James Mwangi",
    date: "2026-02-22",
    series: "Faith Journey",
    scripture: "Hebrews 11:1-6",
    duration: "45 min",
    type: "Sunday Service",
    audioUrl: "#",
    videoUrl: "#",
    notes: "Faith is the substance of things hoped for...",
    views: 145,
  },
  {
    id: 2,
    title: "The Power of Prayer",
    preacher: "Elder Samuel Kariuki",
    date: "2026-02-19",
    series: "Prayer Life",
    scripture: "Matthew 6:5-15",
    duration: "38 min",
    type: "Mid-Week",
    audioUrl: "#",
    videoUrl: null,
    notes: "Jesus taught us how to pray...",
    views: 89,
  },
  {
    id: 3,
    title: "Grace and Mercy",
    preacher: "Rev. James Mwangi",
    date: "2026-02-15",
    series: "God's Character",
    scripture: "Ephesians 2:4-9",
    duration: "52 min",
    type: "Sunday Service",
    audioUrl: "#",
    videoUrl: "#",
    notes: "By grace you have been saved through faith...",
    views: 210,
  },
  {
    id: 4,
    title: "Stewardship and Giving",
    preacher: "Elder Thomas Njoroge",
    date: "2026-02-08",
    series: "Christian Living",
    scripture: "Malachi 3:10",
    duration: "40 min",
    type: "Sunday Service",
    audioUrl: "#",
    videoUrl: "#",
    notes: "Bring the whole tithe into the storehouse...",
    views: 178,
  },
  {
    id: 5,
    title: "The Great Commission",
    preacher: "Rev. James Mwangi",
    date: "2026-02-01",
    series: "Mission",
    scripture: "Matthew 28:18-20",
    duration: "48 min",
    type: "Sunday Service",
    audioUrl: "#",
    videoUrl: "#",
    notes: "Go and make disciples of all nations...",
    views: 195,
  },
  {
    id: 6,
    title: "Fruits of the Spirit",
    preacher: "Elder Samuel Kariuki",
    date: "2026-01-25",
    series: "Holy Spirit",
    scripture: "Galatians 5:22-23",
    duration: "42 min",
    type: "Sunday Service",
    audioUrl: "#",
    videoUrl: "#",
    notes: "The fruit of the Spirit is love, joy, peace...",
    views: 167,
  },
];

// ─── GIVING RECORDS ──────────────────────────────────────────────────────────
export const mockGiving = [
  {
    id: 1,
    member: "John Otieno",
    category: "Tithe",
    amount: 5000,
    date: "2026-02-27",
    period: "February 2026",
    method: "M-Pesa",
    receipt: "RCP001",
  },
  {
    id: 2,
    member: "Mary Njeri",
    category: "Offering",
    amount: 2000,
    date: "2026-02-27",
    period: "February 2026",
    method: "Cash",
    receipt: "RCP002",
  },
  {
    id: 3,
    member: "David Kamau",
    category: "Building Fund",
    amount: 10000,
    date: "2026-02-20",
    period: "February 2026",
    method: "Bank Transfer",
    receipt: "RCP003",
  },
  {
    id: 4,
    member: "Ruth Wambui",
    category: "Tithe",
    amount: 3500,
    date: "2026-02-20",
    period: "February 2026",
    method: "M-Pesa",
    receipt: "RCP004",
  },
  {
    id: 5,
    member: "Joseph Mutua",
    category: "Missions",
    amount: 1500,
    date: "2026-02-13",
    period: "February 2026",
    method: "Cash",
    receipt: "RCP005",
  },
  {
    id: 6,
    member: "Esther Wangari",
    category: "Tithe",
    amount: 7500,
    date: "2026-02-13",
    period: "February 2026",
    method: "M-Pesa",
    receipt: "RCP006",
  },
  {
    id: 7,
    member: "Peter Ochieng",
    category: "Pledge",
    amount: 20000,
    date: "2026-02-06",
    period: "February 2026",
    method: "Bank Transfer",
    receipt: "RCP007",
  },
  {
    id: 8,
    member: "Faith Akinyi",
    category: "Tithe",
    amount: 4000,
    date: "2026-02-06",
    period: "February 2026",
    method: "M-Pesa",
    receipt: "RCP008",
  },
];

// ─── USERS ───────────────────────────────────────────────────────────────────
export const mockUsers = [
  {
    id: 1,
    name: "Super Admin",
    email: "superadmin@covenantcloud.org",
    role: "superadmin",
    status: "active",
    lastLogin: "2026-02-27",
    createdAt: "2024-01-01",
    avatar: null,
  },
  {
    id: 2,
    name: "Rev. James Mwangi",
    email: "james.mwangi@church.org",
    role: "pastor",
    status: "active",
    lastLogin: "2026-02-26",
    createdAt: "2024-01-15",
    avatar: null,
  },
  {
    id: 3,
    name: "Elder Samuel Kariuki",
    email: "samuel.kariuki@church.org",
    role: "elder",
    status: "active",
    lastLogin: "2026-02-25",
    createdAt: "2024-02-01",
    avatar: null,
  },
  {
    id: 4,
    name: "Mrs. Grace Wanjiku",
    email: "grace.wanjiku@church.org",
    role: "treasurer",
    status: "active",
    lastLogin: "2026-02-27",
    createdAt: "2024-02-10",
    avatar: null,
  },
  {
    id: 5,
    name: "Mr. Peter Ochieng",
    email: "peter.ochieng@church.org",
    role: "registrar",
    status: "active",
    lastLogin: "2026-02-24",
    createdAt: "2024-03-01",
    avatar: null,
  },
  {
    id: 6,
    name: "Ms. Faith Akinyi",
    email: "faith.akinyi@church.org",
    role: "deputy_registrar",
    status: "active",
    lastLogin: "2026-02-23",
    createdAt: "2024-03-15",
    avatar: null,
  },
  {
    id: 7,
    name: "Mr. David Kamau",
    email: "david.kamau@church.org",
    role: "member",
    status: "active",
    lastLogin: "2026-02-20",
    createdAt: "2024-04-01",
    avatar: null,
  },
  {
    id: 8,
    name: "Mrs. Mary Njeri",
    email: "mary.njeri@church.org",
    role: "member",
    status: "active",
    lastLogin: "2026-02-18",
    createdAt: "2024-04-15",
    avatar: null,
  },
  {
    id: 9,
    name: "Mr. John Otieno",
    email: "john.otieno@church.org",
    role: "member",
    status: "inactive",
    lastLogin: "2026-01-10",
    createdAt: "2024-05-01",
    avatar: null,
  },
  {
    id: 10,
    name: "Elder Thomas Njoroge",
    email: "thomas.njoroge@church.org",
    role: "elder",
    status: "active",
    lastLogin: "2026-02-22",
    createdAt: "2024-01-20",
    avatar: null,
  },
];

// ─── GROUPS ──────────────────────────────────────────────────────────────────
export const mockGroups = [
  {
    id: 1,
    name: "Men's Fellowship",
    description:
      "A fellowship group for men in the church to grow spiritually and support one another.",
    patron: "Elder Samuel Kariuki",
    chairperson: "Mr. Peter Ochieng",
    vice_chairperson: "Mr. David Kamau",
    secretary: "Mr. John Otieno",
    vice_secretary: "Mr. Joseph Mutua",
    treasurer: "Mr. Thomas Njoroge",
    members: 45,
    meetingDay: "Every 2nd Saturday",
    meetingTime: "10:00 AM",
    status: "active",
    isPCMF: false,
  },
  {
    id: 2,
    name: "Women's Guild",
    description:
      "A fellowship group for women dedicated to prayer, service, and spiritual growth.",
    patron: "Elder Thomas Njoroge",
    chairperson: "Mrs. Grace Wanjiku",
    vice_chairperson: "Mrs. Mary Njeri",
    secretary: "Mrs. Esther Wangari",
    vice_secretary: "Ms. Faith Akinyi",
    treasurer: "Mrs. Ruth Wambui",
    members: 62,
    meetingDay: "Every 1st Saturday",
    meetingTime: "09:00 AM",
    status: "active",
    isPCMF: false,
  },
  {
    id: 3,
    name: "Youth Fellowship",
    description:
      "A vibrant group for young people aged 18-35 to fellowship, worship, and serve.",
    patron: "Elder Samuel Kariuki",
    chairperson: "Ms. Faith Akinyi",
    vice_chairperson: "Mr. David Kamau",
    secretary: "Ms. Ruth Wambui",
    vice_secretary: "Mr. Joseph Mutua",
    treasurer: "Mr. John Otieno",
    members: 78,
    meetingDay: "Every Saturday",
    meetingTime: "03:00 PM",
    status: "active",
    isPCMF: false,
  },
  {
    id: 4,
    name: "PCMF",
    description:
      "Presbyterian Church Men's Fellowship - A dedicated fellowship for men committed to faith and service.",
    patron: "Rev. James Mwangi",
    chairperson: "Elder Samuel Kariuki",
    vice_chairperson: "Mr. Peter Ochieng",
    secretary: "Mr. David Kamau",
    vice_secretary: "Mr. Joseph Mutua",
    treasurer: "Elder Thomas Njoroge",
    vice_treasurer: "Mr. John Otieno", // PCMF exclusive role
    members: 38,
    meetingDay: "Every 3rd Saturday",
    meetingTime: "08:00 AM",
    status: "active",
    isPCMF: true,
  },
  {
    id: 5,
    name: "Choir",
    description:
      "The church choir dedicated to leading worship through music and song.",
    patron: "Rev. James Mwangi",
    chairperson: "Mr. David Kamau",
    vice_chairperson: "Ms. Ruth Wambui",
    secretary: "Mrs. Mary Njeri",
    vice_secretary: "Ms. Faith Akinyi",
    treasurer: "Mrs. Esther Wangari",
    members: 25,
    meetingDay: "Every Tuesday & Thursday",
    meetingTime: "05:00 PM",
    status: "active",
    isPCMF: false,
  },
];

// ─── REPORTS DATA ─────────────────────────────────────────────────────────────
export const mockReports = {
  membershipGrowth: [
    { month: "Sep 2025", count: 185 },
    { month: "Oct 2025", count: 192 },
    { month: "Nov 2025", count: 198 },
    { month: "Dec 2025", count: 205 },
    { month: "Jan 2026", count: 210 },
    { month: "Feb 2026", count: 218 },
  ],
  givingByMonth: [
    { month: "Sep 2025", amount: 125000 },
    { month: "Oct 2025", amount: 138000 },
    { month: "Nov 2025", amount: 142000 },
    { month: "Dec 2025", amount: 195000 },
    { month: "Jan 2026", amount: 130000 },
    { month: "Feb 2026", amount: 111500 },
  ],
  givingByCategory: [
    { category: "Tithe", amount: 65000 },
    { category: "Offering", amount: 22000 },
    { category: "Building Fund", amount: 15000 },
    { category: "Missions", amount: 5500 },
    { category: "Pledge", amount: 20000 },
    { category: "Special Offering", amount: 60000 },
  ],
  attendanceByMonth: [
    { month: "Sep 2025", count: 210 },
    { month: "Oct 2025", count: 225 },
    { month: "Nov 2025", count: 218 },
    { month: "Dec 2025", count: 280 },
    { month: "Jan 2026", count: 195 },
    { month: "Feb 2026", count: 230 },
  ],
};

// ─── SETTINGS ─────────────────────────────────────────────────────────────────
export const mockSettings = {
  church: {
    name: "Covenant Cloud Church",
    denomination: "Presbyterian Church of East Africa",
    address: "123 Church Road, Nairobi, Kenya",
    phone: "+254 20 123 4567",
    email: "info@covenantcloud.org",
    website: "www.covenantcloud.org",
    founded: "1985",
    motto: "Building Lives, Transforming Communities",
    logo: "/CovenantCloud Logo.png",
  },
  notifications: {
    emailNotifications: true,
    smsNotifications: true,
    eventReminders: true,
    donationReceipts: true,
    prayerRequestAlerts: true,
    weeklyDigest: false,
  },
  system: {
    currency: "KES",
    dateFormat: "DD/MM/YYYY",
    timezone: "Africa/Nairobi",
    language: "English",
    fiscalYearStart: "January",
  },
};

// ─── DASHBOARD STATS ──────────────────────────────────────────────────────────
export const getDashboardStats = () => ({
  totalMembers: mockMembers.length,
  activeMembers: mockMembers.filter((m) => m.status === "active").length,
  totalDonations: mockDonations.reduce((sum, d) => sum + d.amount, 0),
  monthlyDonations: mockDonations
    .filter((d) => d.date.startsWith("2026-02"))
    .reduce((sum, d) => sum + d.amount, 0),
  upcomingEvents: mockEvents.filter((e) => e.status === "upcoming").length,
  activePrayerRequests: mockPrayerRequests.filter((p) => p.status === "active")
    .length,
  totalSermons: mockSermons.length,
  totalGroups: mockGroups.length,
  recentMembers: mockMembers.slice(0, 5),
  recentDonations: mockDonations.slice(0, 5),
  upcomingEventsList: mockEvents
    .filter((e) => e.status === "upcoming")
    .slice(0, 3),
});
