# Generated by Django 6.0.1 on 2026-03-10 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donation_type', models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Special Offering', 'Special Offering'), ('Pledge', 'Pledge'), ('Building Fund', 'Building Fund'), ('Missions', 'Missions')], default='Tithe', max_length=50)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('M-Pesa', 'M-Pesa'), ('Cheque', 'Cheque')], default='Cash', max_length=50)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Received', 'Received')], default='Received', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Building Fund', 'Building Fund'), ('Missions', 'Missions'), ('Pledge', 'Pledge')], default='Tithe', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('period', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Special', 'Special')], default='Monthly', max_length=20)),
                ('receipt', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giving_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
