# Generated by Django 6.0.1 on 2026-02-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_alter_district_elder_alter_district_secretary_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_approve_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='districts.district'),
        ),
    ]
